tpm2: fix in tpm2 command generator in ordering include statements.
The CL fixes the incorrect include statement sequence, which
TPM2 command generator generates at this time. The change is likely
due to differences in behavior of clang-format compared to the time
when tpm2 source code was genereated.

An example of this problem is as below:

In HandleProcess.c, "tpm_generated.h" is placed in different line by
generator.
  -#include "tpm_generated.h"
   #include "HandleProcess_fp.h"
   #include "Implementation.h"
   #include "TPM_Types.h"
  +#include "tpm_generated.h"

And it causes errors:

In file included from HandleProcess.c:7:0:
  HandleProcess_fp.h:11:1: error: unknown type name TPM_RC
  HandleProcess_fp.h:12:5: error: unknown type name TPM_CC
  HandleProcess_fp.h:13:5: error: unknown type name BYTE
  HandleProcess_fp.h:15:5: error: unknown type name INT32
  HandleProcess_fp.h:18:5: error: unknown type name TPM_HANDLE
  HandleProcess_fp.h:19:5: error: unknown type name UINT32

It was fixed by disabling "-sort-includes" option in clang-format.
The version information of clang-format is as below:

  clang-format --version
  Chromium OS 7.0_pre333878_p20180808-r3 clang-format version 7.0.0
  (/var/cache/chromeos-cache/distfiles/host/egit-src/clang.git
  38ad3c9160e5814ec8cad29a990cf76730c5f20e)
  (/var/cache/chromeos-cache/distfiles/host/egit-src/llvm.git
  40c66c3d40377cf85640b3a35e6ec5c5b1cbc41f) (based on LLVM 7.0.0svn)

BUG=b:113169470
BRANCH=tpm2_generator
TEST=manually generated the codes and tested with Sirrix test-tpm2 tool.
     ./generator/generator ./generator/TPM2_Parts_2_3_4.tgz

Signed-off-by: Namyoon Woo <namyoon@chromium.org>

 Changes to be committed:
	modified:   generator/command_generator.py

Change-Id: I19fae0a2d0c4bb14ceec03021b0b4f3db825f33f
Reviewed-on: https://chromium-review.googlesource.com/1188804
Commit-Ready: Namyoon Woo <namyoon@chromium.org>
Tested-by: Namyoon Woo <namyoon@chromium.org>
Reviewed-by: Vadim Bendebury <vbendeb@chromium.org>